language: c

# Build step
script: 
  - cd build
  - cmake .. && make

# Compile with both clang and gcc
compiler:
  - clang
  - gcc

# We need libsndfile and portaudio to compile
addons:
  apt:
    packages:
      - libsndfile1
      - libportaudio2
