language: c
branches:
  only:
  - master
os:
  - linux
  - osx
script:
  - cd build
  - cmake .. && make

compiler:
  - gcc
  - clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portaudio libsndfile gtk+3 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libsndfile1-dev portaudio2 portaudio19-dev libgtk-3-0-dev; fi
