# Automatic build file for Windows
<<<<<<< HEAD

os: Visual Studio 2015

# environment variables
environment:
  # my_var1: value1
  # my_var2: value2

install:
=======
version: 1.0.{build}
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
os: Visual Studio 2017
>>>>>>> f5dfbcaf021b74acfd64623b72c5d11c3ea667d7

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

before_build:
  - nuget restore

build:
 # parallel: true                  # enable MSBuild parallel builds
 project: MMAI-reverb.sln      # path to Visual Studio solution or project
 # publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
 # publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
 # publish_azure: true             # package Azure Cloud Service projects and push to artifacts
 # publish_nuget: true             # package projects with .nuspec files and push to artifacts
 # publish_nuget_symbols: true     # generate and publish NuGet symbol packages
 # include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  verbosity: normal

# artifacts configuration
artifacts:
  - path: MMAI-reverb\bin #which files and folders to be uploaded to AppVeyor cloud storage during the build, relative to the root of repository
    name: release
    type: c

# Release
deploy:
  # release: product release of v$(appveyor_build_version)
  description: ' ' #Release description
  provider: GitHub
  auth_token:
    secure: Guvs3xHDDpHVNr9GHmPIrHqcYu2UiQ/mMsthESS119NA7kAj34zsZwuz45yOtSGQDlGRkywc6NHhp0Tq5YwSRw== # your encrypted token from GitHub
  # artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: Candice_coding                 # release from a secondary branch
    appveyor_repo_tag: true        # deploy on tag push only
