# Automatic build file for Windows

os: Visual Studio 2015

# environment variables
environment:
  # my_var1: value1
  # my_var2: value2

install:

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration: 
  - Debug
  - Release

build:
 # parallel: true                  # enable MSBuild parallel builds
 # project: MyTestAzureCS.sln      # path to Visual Studio solution or project
 # publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
 # publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
 # publish_azure: true             # package Azure Cloud Service projects and push to artifacts
 # publish_nuget: true             # package projects with .nuspec files and push to artifacts
 # publish_nuget_symbols: true     # generate and publish NuGet symbol packages
 # include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  verbosity: normal

# scripts to run before build
before_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

# to disable automatic builds
#build: off

# Release
deploy:
  # release: product release of v$(appveyor_build_version)
  description: ' ' #Release description
  provider: GitHub
  auth_token:
    secure: Guvs3xHDDpHVNr9GHmPIrHqcYu2UiQ/mMsthESS119NA7kAj34zsZwuz45yOtSGQDlGRkywc6NHhp0Tq5YwSRw== # your encrypted token from GitHub
  # artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
